# Form implementation generated from reading ui file 'design_1_editing.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1927, 1116)
        MainWindow.setStyleSheet("background-color: #FFFFFF;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_t1_b3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_t1_b3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_t1_b3.setFont(font)
        self.pushButton_t1_b3.setStyleSheet("background-color: #00aeef;\n"
"color:#FFFFFF;\n"
"border-radius: 15")
        self.pushButton_t1_b3.setObjectName("pushButton_t1_b3")
        self.gridLayout_2.addWidget(self.pushButton_t1_b3, 13, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.pushButton_t2_b3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_t2_b3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_t2_b3.setFont(font)
        self.pushButton_t2_b3.setStyleSheet("background-color: #ba014e;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_t2_b3.setObjectName("pushButton_t2_b3")
        self.gridLayout_2.addWidget(self.pushButton_t2_b3, 13, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 4, 5, 1, 1)
        self.label_timer = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(240)
        self.label_timer.setFont(font)
        self.label_timer.setStyleSheet("background-color: #FFFFFF;\n"
"border: 6px solid black;\n"
"border-radius: 15\n"
"\n"
"")
        self.label_timer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_timer.setObjectName("label_timer")
        self.gridLayout_2.addWidget(self.label_timer, 4, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 4, 1, 1)
        self.label_team_two_score = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(180)
        self.label_team_two_score.setFont(font)
        self.label_team_two_score.setStyleSheet("background-color: #ba014e;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.label_team_two_score.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_team_two_score.setObjectName("label_team_two_score")
        self.gridLayout_2.addWidget(self.label_team_two_score, 4, 6, 1, 1)
        self.label_clock = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(90)
        self.label_clock.setFont(font)
        self.label_clock.setStyleSheet("background-color: #545f66;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.label_clock.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_clock.setObjectName("label_clock")
        self.gridLayout_2.addWidget(self.label_clock, 1, 4, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_t2_b2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_t2_b2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_t2_b2.setFont(font)
        self.pushButton_t2_b2.setStyleSheet("background-color: #ba014e;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_t2_b2.setObjectName("pushButton_t2_b2")
        self.gridLayout_5.addWidget(self.pushButton_t2_b2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 10, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 7, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_t1_b2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_t1_b2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_t1_b2.setFont(font)
        self.pushButton_t1_b2.setStyleSheet("background-color: #00aeef;\n"
"color:#FFFFFF;\n"
"border-radius: 15")
        self.pushButton_t1_b2.setObjectName("pushButton_t1_b2")
        self.gridLayout_4.addWidget(self.pushButton_t1_b2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 10, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_add_min = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_add_min.setMinimumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_add_min.setFont(font)
        self.pushButton_add_min.setStyleSheet("background-color: #545f66;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_add_min.setObjectName("pushButton_add_min")
        self.gridLayout_6.addWidget(self.pushButton_add_min, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 0, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 2, 1, 1)
        self.pushButton_add_sec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_add_sec.setMinimumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_add_sec.setFont(font)
        self.pushButton_add_sec.setStyleSheet("background-color: #545f66;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_add_sec.setObjectName("pushButton_add_sec")
        self.gridLayout_6.addWidget(self.pushButton_add_sec, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 10, 4, 1, 1)
        self.pushButton_t2_b1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_t2_b1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_t2_b1.setFont(font)
        self.pushButton_t2_b1.setStyleSheet("background-color: #ba014e;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_t2_b1.setObjectName("pushButton_t2_b1")
        self.gridLayout_2.addWidget(self.pushButton_t2_b1, 7, 6, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 4, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 7, 4, 1, 1)
        self.spinBox_t1_b1 = QtWidgets.QSpinBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_t1_b1.setFont(font)
        self.spinBox_t1_b1.setStyleSheet("background-color: #00aeef;\n"
"color:#FFFFFF;\n"
"border-radius: 15")
        self.spinBox_t1_b1.setMinimum(-99)
        self.spinBox_t1_b1.setObjectName("spinBox_t1_b1")
        self.gridLayout_2.addWidget(self.spinBox_t1_b1, 8, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem12, 0, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem13, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem14, 0, 2, 1, 1)
        self.pushButton_sub_sec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_sub_sec.setMinimumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_sub_sec.setFont(font)
        self.pushButton_sub_sec.setStyleSheet("background-color: #545f66;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_sub_sec.setObjectName("pushButton_sub_sec")
        self.gridLayout.addWidget(self.pushButton_sub_sec, 0, 3, 1, 1)
        self.pushButton_sub_min = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_sub_min.setMinimumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_sub_min.setFont(font)
        self.pushButton_sub_min.setStyleSheet("background-color: #545f66;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_sub_min.setObjectName("pushButton_sub_min")
        self.gridLayout.addWidget(self.pushButton_sub_min, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 11, 4, 1, 1)
        self.spinBox_t1_b3 = QtWidgets.QSpinBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_t1_b3.setFont(font)
        self.spinBox_t1_b3.setStyleSheet("background-color: #00aeef;\n"
"color:#FFFFFF;\n"
"border-radius: 15")
        self.spinBox_t1_b3.setMinimum(-99)
        self.spinBox_t1_b3.setObjectName("spinBox_t1_b3")
        self.gridLayout_2.addWidget(self.spinBox_t1_b3, 14, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 9, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 12, 2, 1, 1)
        self.textEdit_team_one = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_team_one.setMinimumSize(QtCore.QSize(350, 0))
        self.textEdit_team_one.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.textEdit_team_one.setFont(font)
        self.textEdit_team_one.setStyleSheet("background-color: #00aeef;\n"
"color:#FFFFFF;\n"
"border-radius: 15")
        self.textEdit_team_one.setObjectName("textEdit_team_one")
        self.gridLayout_2.addWidget(self.textEdit_team_one, 1, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 15, 2, 1, 1)
        self.textEdit_team_two = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_team_two.setMinimumSize(QtCore.QSize(350, 0))
        self.textEdit_team_two.setMaximumSize(QtCore.QSize(16777215, 70))
        self.textEdit_team_two.setStyleSheet("background-color: #ba014e;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.textEdit_team_two.setObjectName("textEdit_team_two")
        self.gridLayout_2.addWidget(self.textEdit_team_two, 1, 6, 1, 1)
        self.spinBox_t2_b1 = QtWidgets.QSpinBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_t2_b1.setFont(font)
        self.spinBox_t2_b1.setStyleSheet("background-color: #ba014e;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.spinBox_t2_b1.setMinimum(-99)
        self.spinBox_t2_b1.setObjectName("spinBox_t2_b1")
        self.gridLayout_2.addWidget(self.spinBox_t2_b1, 8, 6, 1, 1)
        self.spinBox_t2_b2 = QtWidgets.QSpinBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_t2_b2.setFont(font)
        self.spinBox_t2_b2.setStyleSheet("background-color: #ba014e;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.spinBox_t2_b2.setMinimum(-99)
        self.spinBox_t2_b2.setObjectName("spinBox_t2_b2")
        self.gridLayout_2.addWidget(self.spinBox_t2_b2, 11, 6, 1, 1)
        self.spinBox_t2_b3 = QtWidgets.QSpinBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_t2_b3.setFont(font)
        self.spinBox_t2_b3.setStyleSheet("background-color: #ba014e;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.spinBox_t2_b3.setMinimum(-99)
        self.spinBox_t2_b3.setObjectName("spinBox_t2_b3")
        self.gridLayout_2.addWidget(self.spinBox_t2_b3, 14, 6, 1, 1)
        self.spinBox_t1_b2 = QtWidgets.QSpinBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_t1_b2.setFont(font)
        self.spinBox_t1_b2.setStyleSheet("background-color: #00aeef;\n"
"color:#FFFFFF;\n"
"border-radius: 15")
        self.spinBox_t1_b2.setMinimum(-99)
        self.spinBox_t1_b2.setObjectName("spinBox_t1_b2")
        self.gridLayout_2.addWidget(self.spinBox_t1_b2, 11, 2, 1, 1)
        self.pushButton_t1_b1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_t1_b1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_t1_b1.setFont(font)
        self.pushButton_t1_b1.setStyleSheet("background-color: #00aeef;\n"
"color:#FFFFFF;\n"
"border-radius: 15")
        self.pushButton_t1_b1.setObjectName("pushButton_t1_b1")
        self.gridLayout_2.addWidget(self.pushButton_t1_b1, 7, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem18, 16, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 4, 1, 1, 1)
        self.label_team_one_score = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(180)
        self.label_team_one_score.setFont(font)
        self.label_team_one_score.setStyleSheet("background-color: #00aeef;\n"
"color:#FFFFFF;\n"
"border-radius: 15")
        self.label_team_one_score.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_team_one_score.setObjectName("label_team_one_score")
        self.gridLayout_2.addWidget(self.label_team_one_score, 4, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem21)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem22, 0, 8, 1, 1)
        self.pushButton_confirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_confirm.setMinimumSize(QtCore.QSize(400, 75))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setStyleSheet("background-color: #88D49E;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout_8.addWidget(self.pushButton_confirm, 0, 11, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(400, 75))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setStyleSheet("background-color: #545f66;\n"
"color: #FFFFFF;\n"
"border-radius: 15")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_8.addWidget(self.pushButton_cancel, 0, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem23, 0, 6, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem24, 0, 4, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem25, 0, 3, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem26, 0, 9, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem27, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem28, 0, 7, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem29, 0, 12, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem30, 0, 10, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem31, 0, 5, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem32, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_t1_b3.setText(_translate("MainWindow", "Button 3"))
        self.pushButton_t2_b3.setText(_translate("MainWindow", "Button 3"))
        self.label_timer.setText(_translate("MainWindow", "00:00"))
        self.label_team_two_score.setText(_translate("MainWindow", "00"))
        self.label_clock.setText(_translate("MainWindow", "11:02pm"))
        self.pushButton_t2_b2.setText(_translate("MainWindow", "Button 2"))
        self.pushButton_t1_b2.setText(_translate("MainWindow", "Button 2"))
        self.pushButton_add_min.setText(_translate("MainWindow", "+ Minute"))
        self.pushButton_add_sec.setText(_translate("MainWindow", "+ Second"))
        self.pushButton_t2_b1.setText(_translate("MainWindow", "Button 1"))
        self.pushButton_sub_sec.setText(_translate("MainWindow", "- Second"))
        self.pushButton_sub_min.setText(_translate("MainWindow", "- Minute"))
        self.textEdit_team_one.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:600;\">Team One</span></p></body></html>"))
        self.textEdit_team_two.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:600;\">Team Two</span></p></body></html>"))
        self.pushButton_t1_b1.setText(_translate("MainWindow", "Button 1"))
        self.label_team_one_score.setText(_translate("MainWindow", "00"))
        self.pushButton_confirm.setText(_translate("MainWindow", "Confirm"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
